[package]
name = "plasma"
version = "0.1.0"
authors = ["Chris Mounce <christophermounce@gmail.com>"]

[dependencies]
cgmath = "0.14.1"
getopts = "0.2"
gif = "0.9"
ordered-float = "0.5"
rand = "0.3"
rustc-serialize = "0.3"
sdl2 = "0.30"
